### ISSUE TITLE
Writer did not close gracefully.

### ISSUE THREAD

**Issue by earsnot** [jetperch/pyjoulescope_server#1]
Hi @mliberty1
Awesome stuff you have going here. Very impressed by the joulescope so far.

We are developing a C# library that can communicate with the server you have written in python.
I can see, that in your example client.py, you are awaiting a receiver_task in the end.
I have implemented an async connection with a receiver that takes care of the communication, and everything is working fine, except when closing the connection, then i get the following console output from the server:
ERROR:2022-11-08 08:35:52,752:server.py:380:joulescope_server.server:handle_client error
Traceback (most recent call last):
  File "C:\Users\ara\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
\joulescope_server\server.py", line 354, in run
    msg = await framer.treceive(self._reader)
\joulescope_server\framer.py", line 105, in treceive
    tag, payload = await receive(reader)
\joulescope_server\framer.py", line 89, in receive
    header = await reader.readexactly(HEADER_LENGTH)
\Python38\lib\asyncio\streams.py", line 740, in readexactly
    await self._wait_for_data('readexactly')
\Python38\lib\asyncio\streams.py", line 534, in _wait_for_data
    await self._waiter
\Python38\lib\asyncio\proactor_events.py", line 280, in _loop_reading
    data = fut.result()
\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
\Python38\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] The specified network name is no longer available
WARNING:2022-11-08 08:35:52,756:server.py:386:joulescope_server.server:Writer did not close gracefully
INFO:2022-11-08 08:35:52,756:server.py:250:joulescope_server.server:_async_task done
INFO:2022-11-08 08:35:52,757:server.py:392:joulescope_server.server:ClientManager.run done

I am pretty clueless on how to solve this. The server sometimes becomes unresponsive after this has happened.
Any pointing in the right direction would be greatly appreciated.
//Anders

**Comment by earsnot** [comment]
Hi @mliberty1 
I have been cloning the repo and running it from there using the python -m joulescope_server. 
I still get the same behaviour when installing it with pip and running it directly. 
I suspect I need to await some event.
At the moment, I am facing different issues however. Is there a forum I should ask questions instead?

**Comment by mliberty1** [comment]
Hi @earsnot  - If you have general Joulescope questions, the best place is the [Joulescope forum](https://forum.joulescope.com).  If you have questions specific to this pyjoulescope_server package, I just opened "Discussions" on the GitHub repo.  Visit the repo and click on the **Discussions** tab.

**Comment by mliberty1** [comment]
We still have an outstanding unexplained behavior with a C# client (see [discussion](https://github.com/jetperch/pyjoulescope_server/discussions/3)).  However, the example python client now closes cleanly, so I am going to close this issue.
